[tool.poetry]
name = "jumpstart-model-info-resolver"
version = "0.1.0"
description = "Resolve model info for jumpstart models"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "jumpstart_model_info_resolver"}]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
boto3 = "^1.28.37"
sagemaker = "^2.182.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
