---
blank_issues_enabled: false
contact_links:
  - name: 💬 General Question
    url: https://github.com/aws-samples/aws-genai-conversational-rag-reference/discussions/categories/q-a
    about: Please ask and answer questions as a discussion thread
