// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
/* eslint-disable */
import * as path from 'path';
import { Asset } from 'aws-cdk-lib/aws-s3-assets';
import { IConstruct } from 'constructs';

/**
 * Asset path for src/ai/llms/models/sentence-transformer/custom.asset
 */
export const CUSTOM_ASSET_PATH = path.join(__dirname, '../../../../../assets/ai/llms/models/sentence-transformer/custom');

/**
 * Asset construct for src/ai/llms/models/sentence-transformer/custom.asset
 */
export class CustomAsset extends Asset {
  constructor(scope: IConstruct, id: string) {
    super(scope, id, {
      "path": CUSTOM_ASSET_PATH,
    })
  }
}